### ISSUE TITLE
DoA testing implementation Checklist

### ISSUE THREAD

**Issue by ibrahimhuycn** [SwatInc/CD4#112]
# Order Entry Fileds

| Order Entry Field                                       | Billing Field                                   |
|:------------------------------------------------------- | ----------------------------------------------- |
| Episode number                                          | Memo Number                                     |
| Sample Number                                           | `CONCAT("(Memo number)", "form number")`        |
| Collection Site                                         | "Police"                                        |
| NDA.SampleCollectedDateTime & actual collected DateTime | Sample CollectedDateTime                        |
| National ID/PP                                          | Custody Number                                  |
| Fullname                                                | Custody Number                                  |
| Gender (Set as UNKNOWN)                                 | NA                                              |
| Birthdate (Set as `DateTime.Today()`)                   | NA                                              |
| Phone Number (set as 1234 or NDA number)                | NA                                              |
| Age (set as Zero)                                       | NA                                              |
| Nationality (Set as UNKNOWN)                            | NA                                              |
| Address                                                 | Always C/O National Drug Agency K.Male' for DoA |
| Tests Selected                                          | DoA Panel                                       |
| Clinical Details (NA)                                   | NA                                              |

- [x] Episode Number: 
- [x]  CustodyNumber: Name
- [x]  ADDRESS: nDA ADDRESS [C/O National Drug Agency K.Male']
- [x]  CustodyNumber: nidPp (varchar 50)
- [x]  Gender: Unknown
- [x]  DOB: Date.today()
- [x]  PhoneNumber: 1324567
- [x]  nationality: Unknown

# results (Complete)
- [x]  ResultOP ==> From test Test
- [x]  ResultBENZ1 ==> From test Test
- [x]  ResultBENZ2 ==> From test Test
- [x]  ResultCOC ==> From test Test
- [x]  ResultTHC ==> From test Test
- [x]  ResultAMPH ==> From test Test
- [x]  ResultETG ==> From test Test
- [x]  ResultAM ==> From test Test

# Get Data from Billing Side
- [x]  MemoNumber
- [x]  CustodyNumber
- [x]  RegisterNumber
- [x]  SampleCollectedDateAndTime ==> CollectedDateTime (collected at police)
- [x]  SampleReceivedBy
- [x]  SampleReceivedDateTime

# Get data from Analyser
- [x]  SampleProcessedDateAndTime == from analyser Or Query time

# Manually Batched Update
- [x]  CalAndControlsValidatedBy
- [x]  TestedBy

# Manually batched on ResultEntry Screen sub view
- [x]  ReportedDate

Evidence Investigator ==> Supports Query mode
Datona On-Line Real-time mode== query mode

**Comment by ibrahimhuycn** [comment]
# Additional database changes for accommodating National Drug Agency tracking requirements

## 1. New database Fields

| Fields                                        | Data Type  |
| --------------------------------------------- | ---------- |
| RegisterNumber (Institute Assigned PatientId) | `bigint`   |
| SampleReceivedByUserId                        | `int`      |
| CalAndControlsValidatedByUserId               | `int`      |
| TestedByUserId                                | `int`      |
| SampleProcessedAt                             | `datetime` |
| ReportedAt                                    | `datetime` |



## 2. Alterations to Existing Tables

1. Add fields to`dbo.Users` 
   - `dbo.Users.FullNameLocal` in `nvarchar(100)` to allow the users name in any language

1. `dbo.Patient`
   - RegisterNumber as `dbo.Patient.InstituteAssignedPatientId`

## 3. New Tables

### `dbo.NdaActionTracking`

| Field        | Data Type        | Relation              |
| ------------ | ---------------- | --------------------- |
| Id           | `int INDENTITY`  | PK                    |
| Sid          | `int`            | FK `dbo.Sample.Id`    |
| NdaLookUpId  | `int`            | FK `dbo.NdaLookup.Id` |
| ActionUserId | `int`            | FK `dbo.Users.Id`     |
| CreatedAt    | `datetimeoffset` |                       |
| CreatedBy    | `int`            | FK `dbo.Users.Id`     |

### `dbo.NdaTimeTracking`

| Field       | Data Type        | Relation              |
| ----------- | ---------------- | --------------------- |
| Id          | `int INDENTITY`  | PK                    |
| Sid         | `int`            | FK `dbo.Sample.Id`    |
| NdaLookupId | `int`            | FK `dbo.NdaLookup.Id` |
| CreatedAt   | `datetimeoffset` |                       |
| CreatedBy   | `int`            | FK `dbo.Users.Id`     |

### `dbo.NdaLookup`

| Field        | Data Type       | Relation          |
| ------------ | --------------- | ----------------- |
| Id           | `int INDENTITY` | PK                |
| Description  | `varchar(50)`   |                   |

**Comment by ibrahimhuycn** [comment]
- [ ] Automatic Result interpretations
